### PR TITLE
Swift 1.2 compatibility changes.

### PR DESCRIPTION
**Pull request by brynbellomy**
These changes make Starscream build with Swift 1.2.

### CODE REVIEW

**Comment by daltoniam** [comment]
Thanks, I appreciate it. I will create a branch and merge it there until Swift 1.2 is out of beta.

**Comment by daltoniam** [comment]
@brynbellomy I created a `swift-1.2` branch and pulled your changes in manually. I wasn't sure how to change the PR to a different branch, but thank you again for the PR.

**Comment by brynbellomy** [comment]
Oh, yeah, my bad... I should've done that on my end.  Great library, btw!

**Comment by daltoniam** [comment]
No big deal, was pretty quick process. Thanks!

**Pull request closed without merging**
