### PR TITLE
Property for enabling only certain cipher suites for the WSS connection

### PR DESCRIPTION
**Pull request by lbanders**
We have the option of enabling only certain cipher suites to improve the security on the WSS connections. We have added a **enabledSSLCipherSuites** property which is an array of **SSLCipherSuite**. To disable, simply set to **nil**.

The selected cipher suites must be valid for the platform. If an error occurs while enabling the cipher suites for a stream, we will fail the connection.

### CODE REVIEW

**Comment by daltoniam** [comment]
Cool, thanks for the PR. Three things: 

- can we remove the `NSLog` statements?
- can we just call `disconnectStream(error)` and not `doDisconnect(error)`? (I know it is like that on the other security stuff now ( [line 262](https://github.com/daltoniam/Starscream/blob/master/WebSocket.swift#L262) ), but I think that is unnecessary and can be removed.)
-   Can we return on both the failure cases after `disconnectStream`? We probably don't want it to start the runloop part when it wouldn't connect properly anyway.

Thanks! Any question please let me know.

**Comment by lbanders** [comment]
Yes sure - I will updated the PR with those changes. They sounds like reasonable changes. 
We will probably also make one for setting the TLS protocols, but a PR will come for that later.

**Comment by pcoltau** [comment]
I have corrected the code with respect to the review comments. Please review it again.

**Comment by daltoniam** [comment]
looks good. Thanks!

**Pull request merged**
