### PR TITLE
Fixed Swift 5 deprecation warnings

### PR DESCRIPTION
**Pull request by serkrapiv**
Fixing the warnings that appear with transition to Swift 5. Should be double-checked though, I'm not sure that all these changes are safe.

### CODE REVIEW

**Comment by WyattMufson** [comment]
This is being done in #653

**Comment by plivesey** [comment]
Thanks for the context. I'll follow those changes.

**Comment by patpatpat123** [comment]
Hello StarScream Team,

Just wanted to cheer for you guys, as this project is quite awesome.
After updating to Swift5, I also have the same warnings.
Looking forward to the merge and a possible 3.1 that will address the warnings.

Thank you

**Comment by daltoniam** [comment]
I'm going to go ahead and close this out as it is related to the old 3.X.X codebase. Thanks again for the PR!

**Pull request closed without merging**
