### PR TITLE
Added callbacks for pings and pongs

### PR DESCRIPTION
**Pull request by Elethier**
I took the changes from #268 and reimplemented them in Swift 3. These changes add callbacks and a delegate for apps to listen for when a ping has been sent, a ping has been received, and a pong has been sent.

I should also note that I was having trouble with running the tests, as stated in issue #297. Let me know if there's any test failures.

@daltoniam Please review.

### CODE REVIEW

**Comment by acmacalister** [comment]
@Elethier more of an exploration question. I understand this is used for testing, but why do you need to ping/pong the server in the first place? Most WebSocket libraries (this one included) handle the ping/pong behavior for you...

**Comment by Elethier** [comment]
@acmacalister For my project, we're using these callbacks for purely diagnostic purposes. The code has been invaluable in diagnosing our connection issues with the hardware we're trying to connect to. I was able to check what time we were sending pongs, the exact time a ping was sent down the OutputStream, etc.

We are _not_ using the callbacks to implement ponging behavior, since that's already implemented within the library. I can see how this could cause confusion, though. Maybe I should add some documentation. I'm open to suggestions.

**Comment by cpinski** [comment]
@Elethier can we add some documentation as to how these callback would be used? I think that will help other developers understand the meaning for these callbacks and correctly use them.

**Comment by Elethier** [comment]
@cpinski I added some documentation. Although some of it looks a little redundant...please comment if you think there's some tags that could be removed.

**Comment by Elethier** [comment]
@daltoniam @acmacalister What do you two think? Does this PR seem suitable to merge in?

**Comment by daltoniam** [comment]
I see the value in debugging with this, but I fear it would cause confusion from a implementation stand point and its main value is in debugging. It doesn't inherently add much to a normal user outside of being able to debug which is hopefully not that often 😁.  Also the `onPong` was change to a suitable name, but that will cause some minor issues with backwards compatibility (not a big deal, just as a note). I guess my concern is this doesn't add much value to the typical user of the library and is only really handy for those of us that work on the code base directly to debug with. Nothing wrong with the code, just more a question if it adds enough value and if there is a way we might be able to make it less intrusive. I'm certainly open to suggestions, but I haven't thought of a way yet to accomplish this yet.

**Comment by Elethier** [comment]
@daltoniam Perhaps I could add something like a `WebSocketDebugDelegate` on top of the existing functionality? I'm worried that if someone else needs to do the debugging I did, they'll have to fork the library and reimplement these changes. Then again, we'd be forcing people to include debug code into production builds...unless I did an `#if DEBUG` inside of the library.

**Comment by Elethier** [comment]
@daltoniam I wanted to bring this up again, since this pull request has been up for a while. Do you think it would be valuable to merge this in? Do you think a `WebSocketDebugDelegate` would be a better approach? Or should I just close this pull request? 

Since implementing these changes in our project, we haven't had any major connection issues, so I wouldn't mind removing the related code in our project and closing this.

**Comment by jakeholland** [comment]
@daltoniam I will be taking over this PR for @Elethier from this point forward. Just curious if you had any open questions?

**Comment by hishnash** [comment]
This would be nice, would work well along side the features in https://github.com/daltoniam/Starscream/pull/337

**Comment by acmacalister** [comment]
@jakeholland @Elethier apologies on the massive delay here. I like @hishnash idea of adding this to the `AdvancedWebSocketDelegate`. I'm going to merge the other PR tomorrow, would you mind updating this PR to use that instead? Again apologies on the delay.

**Comment by jakeholland** [comment]
I should be able to get to this tomorrow I think.

**Comment by daltoniam** [comment]
@jakeholland again sorry about the delay, but finally merged 😄. One of these days I will be fast at merging PRs. Thanks again.

**Comment by jakeholland** [comment]
@daltoniam - I  finally got around to making the changes to move the ping/pong callbacks into the new AdvancedWebSocketDelegate 😃

**Comment by daltoniam** [comment]
@jakeholland Thanks! No worries, I'm not exactly the fastest on open source anymore either 😬. I'm going to create a Swift 4 branch and merge these changes into that since it does have some minor backwards compatibility breaking changes with the pong stuff.

**Comment by zayats77** [comment]
Hi
Please merge this pull request.

**Pull request closed without merging**
