### PR TITLE
Bumped to Xcode 11 and swift 5 support

### PR DESCRIPTION
**Pull request by pushp1989**

### CODE REVIEW

**Comment by noobs2ninjas** [comment]
Haha I'm from Parse and was just coming over to check on Starscreams Xcode 11 support as ParseLiveQuery uses it and I noticed this pull request. I literally dealt with this last night updating Parse. The error is from fuzzy and simply needs the cocoa pods version updated. We went with 1.7.5 but you may be able to get away with less as you don't use things like jazzy for generating docs.

**Comment by pushp1989** [comment]
Hey Nathan, We have to travis for CI/CD and We are doing development on top of it. I don't think the file we have change is going to impact your code in any ways. I understand your concern but you can merge these file as it will be help for those who are developing on Xcode 11 and swift version 5.

**Comment by noobs2ninjas** [comment]
You’re right. Was just stopping by to give you the tip to update your cocoapods version for the fourflusher error on your Travis build.

**Comment by pushp1989** [comment]
We are not using Cocoapods. we are using Carthage for managing dependency. Which version should I need to get my worked done?

**Comment by noobs2ninjas** [comment]
That may be what you are using inside the project itself. However, your travis build is validating your podspec and building it using cocoapods. 

```
    - ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: ). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/fourflusher-2.2.0/lib/fourflusher/find.rb:106:in `usable_simulators'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/fourflusher-2.2.0/lib/fourflusher/find.rb:97:in `simulator'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/fourflusher-2.2.0/lib/fourflusher/xcodebuild.rb:7:in `destination'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/validator.rb:923:in `xcodebuild'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/validator.rb:617:in `block in build_pod'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:145:in `message'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/validator.rb:607:in `build_pod'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/validator.rb:371:in `block in perform_extensive_analysis'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/validator.rb:359:in `each'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/validator.rb:359:in `perform_extensive_analysis'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/validator.rb:128:in `validate'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/command/lib/lint.rb:75:in `block in run'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/command/lib/lint.rb:60:in `each'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/command/lib/lint.rb:60:in `run'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
/Users/travis/.rvm/gems/ruby-2.4.5/bin/pod:23:in `load'
/Users/travis/.rvm/gems/ruby-2.4.5/bin/pod:23:in `<main>'
/Users/travis/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `eval'
/Users/travis/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `<main>'
) during validation.
[!] Starscream did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/command/lib/lint.rb:92:in `block in run'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/command/lib/lint.rb:60:in `each'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/command/lib/lint.rb:60:in `run'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/Users/travis/build/daltoniam/Starscream/vendor/bundle/ruby/2.4.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
```
What you need to do is run `bundler update` in terminal and commit the changes to `Gemfile.lock`. If you don't have bundler simply run `sudo gem install bundler`. Before committing make sure the `Gemfile.lock` cocoapods version has updated greater than 1.6.1. It should say cocoapods (1.7.5) somewhere inside that `Gemfile.lock` file.

**Comment by noobs2ninjas** [comment]
If you cant figure it out let me know and I'll do it and commit and merge it into your fork so that it will update here.

**Comment by noobs2ninjas** [comment]
What I'm not sure about is why its running the release.sh script during a normal pull request which is whats building this using cocoapods.

**Comment by daltoniam** [comment]
I'm going to go ahead and close this out as it is related to the old 3.X.X codebase. Thanks again for the PR!

**Pull request closed without merging**
