### PR TITLE
update to swift 4 manifest

### PR DESCRIPTION
**Pull request by nuclearace**
The Swift 3 manifest will be going away in Swift 5.

@daltoniam I'm not sure the story about the PRs looking to fix the issues around the dependencies, but I'm thinking about moving those to internal system targets (something new introduced in Swift 4.2.) Thoughts?

### CODE REVIEW

**Comment by daltoniam** [comment]
Thanks. I still needed to get this done, I appreciate you doing this. Yeah, #520 does fix an issue with Carthage builds, but it also introduces some Objective-C bridging which I don't want to do, because that would break Linux support (which I still want to do) and I think it might break the SPM builds. All these package managers never want to play nice together 😬. Thanks again.

**Comment by nuclearace** [comment]
@daltoniam Yeah I actually tried to get linux working this weekend. It's going to be pretty painful I think, you'll have to get rid of the CFNetworking stuff. Since although the functions are _defined_ in open source core foundation, actually trying to use them runs into this gem.



So I think to really get linux support your best bet is to use SwiftNIO for that. But I'm not sure how that fits into the work with using the Networking lib. Since I don't think that is available on Linux either.

**Comment by fassko** [comment]
Apple has released https://github.com/apple/swift-nio-transport-services for this task. Also there is https://github.com/apple/swift-nio-examples where some of examples will be kept.
In near future I'm looking more into SwiftNIO and how it can benefit also this project.

**Comment by nuclearace** [comment]
@fassko Sweet. I think if this lib could use SwiftNIO for all platforms it would greatly ease the maintenance cost compared to a ton of `#if os` checks. (Which are probably still going to be needed)

**Comment by daltoniam** [comment]
@nuclearace Well that is disappointing but not unexpected 😞. I agree with y'all, we should probably look at SwiftNIO. I might be holding on to an outdated version of the project, but I try to balance simplicity and bringing in a lot of dependencies which has been has been a bit of a pain with all the package managers. I guess that is already the status quo, so probably just makes sense to unify on a system.

**Comment by vkedwardli** [comment]
@daltoniam  if #520 won't be merged, please consider https://github.com/daltoniam/Starscream/pull/482, thanks

**Pull request merged**
