### PR TITLE
HTTP Proxy support

### PR DESCRIPTION
**Pull request by HarveyHu**
* HTTP Proxy support

### CODE REVIEW

**Comment by Hamed13631345** [comment]
ok

**Comment by DazChong** [comment]
I'm testing with this PR and it works with HTTP_PROXY without issue, hope it get merged ASAP as it's essential for working in corporate environment.  Thanks @HarveyHu , I'm using ur fork as solution for now.

**Comment by fassko** [comment]
Can you please check the conflicts? Thanks!

**Comment by DazChong** [comment]
I'd submitted a PR for the fix https://github.com/daltoniam/Starscream/pull/580.

Some other info:
- I noticed that 3.0.6 mentioned HTTP Proxy support, but it's not working for me.
- I tested with new Network.framework (support proxy) to connect to the server and indeed it's able to find the host and connect, but not with branch `xcode-10`.

**Comment by fassko** [comment]
@DazChong Could you please check the merge conflicts? Thanks!

**Comment by DazChong** [comment]
It is there, 
https://github.com/daltoniam/Starscream/pull/580

**Comment by HarveyHu** [comment]
@DazChong I haven't checked this for a while. Thanks for the support. 
And also I just added some protection for kCFProxyPortNumberKey to avoid crashes when people are using other proxy types instead of HTTP Proxy.

**Comment by neiker** [comment]
Any idea on when this will be merged?

**Comment by acmacalister** [comment]
The codebase has actually under gone a major refactor which has `Network.framework` support. Since that is able to handle proxy connections transparently, I'm going to close this for now. Feel free to check it out here #653.

**Pull request closed without merging**
