### PR TITLE
Fixes embedded dylibs/frameworks only run on iOS8 warning by ignoring linker warnings

### PR DESCRIPTION
**Pull request by artman**
XCode6.1 (falsely) warns that dylibs don't work on <iOS8. Suppressing this warning with linker flags for now.

### CODE REVIEW

**Comment by pizthewiz** [comment]
While dynamic frameworks may run on iOS 7, App Store submission will be _rejected_ (TestFlight too) if a bundled framework is not built with a deployment target of iOS 8+, see realm/realm-cocoa#900 and Hearst-DD/ObjectMapper#23 for other cases of this. The realm team worked around this by creating a static framework target for iOS 7 and dynamic framework target for iOS 8 use, or one could of course just pull the files in directly.

So quieting the warning masks the issue a bit no?

**Comment by daltoniam** [comment]
@pizthewiz that is a good point. Personally for apps that I have to support iOS 7 on, I have just been pulling the files in directly. I know that isn't ideal, but since iOS 7 is going probably fall off as a "supported development version" when iOS 9 drops, it might be an ok compromise. If there is the demand (or a pull request), I could see creating a static lib like realm has done.

**Comment by pizthewiz** [comment]
> for apps that I have to support iOS 7 on, I have just been pulling the files in directly

Yep, that technique has been suggested for the ObjectMapper library too. It could be more formalized by setting the framework deployment target to iOS 8 and add a mention in the README - this would at least put iOS 8 on the fully supported path. The current form of the framework target is not usable for App Store submission for iOS 7 _or_ iOS 8, and suppressing the warnings just further obscures the core issue no?

**Comment by daltoniam** [comment]
Agreed. The README should probably update to reflect this. That is a good point, I will change the framework to allow this as well. Thanks for bring it up.

**Pull request merged**
