### PR TITLE
reference to calling websocket instance

### PR DESCRIPTION
**Pull request by cyphercommunications**
Not sure if this would detract from the clean interface you have, but I've found it to be useful

### CODE REVIEW

**Comment by acmacalister** [comment]
@cyphercommunications appreciate the PR. What where some of the use cases you found useful exposing the underlining socket in the interface?

**Comment by cyphercommunications** [comment]
We use a hybrid app on iOS that requires multiple voip web sockets to be used. We have written a wrapper in javascript that allows the web view to use the existing browser WebSocket api, but still keep the socket listening while the device sleeps.

It may not be the best technique, but we found exposing the underlining socket to be necessary in order to know which socket to trigger the correct handlers for on the javascript side.

**Comment by nicolasbigot** [comment]
+1 for this, this is something I really need too (one unique delegate for multiple WebSocket instances)

**Comment by daltoniam** [comment]
Alright, I concede :smile: . Just for reference this was discussed in #42 as well.

**Pull request merged**
