### PR TITLE
Fix Redefinition of module error in Xcode ≧ 8.3, Take 2

### PR DESCRIPTION
**Pull request by vkedwardli**
Second attempt to fix this bug (first failed attempt:https://github.com/daltoniam/Starscream/pull/465)

Using dynamic generated modulemap now to avoid the Xcode bug, according to [Xcode 8.3 release notes](https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html):

> When building a framework that has module maps in both the source and the install directories that define the same module, the compiler will show a redefinition message. (28638816)

Reference:
https://github.com/ResearchKit/ResearchKit/issues/922
https://github.com/grpc/grpc/issues/10355

Should can fix the error mentioned by @rhishikeshj in  https://github.com/daltoniam/Starscream/issues/361#issuecomment-346810549

### CODE REVIEW

**Comment by vkedwardli** [comment]
@shams-ahmed My PR supports the original Xcode project and cocoapods generated project, I think I don't have anything to add, do inform me if you find any bug, thanks

**Comment by daltoniam** [comment]
This looks cool, Thanks! It would probably be best to test it with all 3 package managers (Swift Package Manager, CocoaPods, and Carthage). It is quite a process to get them to play nicely with the different dependencies (the commonCrypto and zlib) and It would be great if this removes that warning and simplifies all that building a bit 😄.

**Comment by bayareahank** [comment]
We ran into similar Starscream Carthage module redefinition build errors in ParseLiveQuery: 
[parse-community/ParseLiveQuery-iOS-OSX#159](https://github.com/parse-community/ParseLiveQuery-iOS-OSX/issues/159)
Hope this fix can solve the problem.

**Comment by vkedwardli** [comment]
@bayareahank may be you could help on verifying on Carthage to speed up accepting

**Comment by bayareahank** [comment]
Sure. 

Disclaimer that I only used Carthage to pull directly from github before, if there is some pointers as to how to build with pull request, that would be helpful.

**Comment by vkedwardli** [comment]
@bayareahank try it from my branch
```git "https://github.com/vkedwardli/Starscream.git" "fix-module-redefinition"```

**Comment by bayareahank** [comment]
I tried the change in ParseLiveQuery, the app build still runs into errors, though the detailed error message changed a bit from previous one. 

Previously it complains "redefinition of module 'SSCZLib' and module 'SSCommonCrypto',
thus could not build Objective-C module 'Starscream' "
https://github.com/parse-community/ParseLiveQuery-iOS-OSX/issues/159

This time it fails to build Object-C module 'SSCZlib'. The detailed error message is: 
~/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3_9E145/Starscream/897f51388f6b1504f1093f2ca7dcd302e2b3128e/Build/Products/Release-iphonesimulator/StarscreamModuleMap/module.modulemap:6:8: error: import of shadowed module 'SSCommonCrypto'
module SSCommonCrypto [system] {
       ^
~/tmp/liveStarstream/Carthage/Checkouts/ParseLiveQuery-iOS-OSX/Carthage/Checkouts/Starscream/zlib/module.modulemap:6:8: note: previous definition is here
module SSCommonCrypto [system] {
       ^
~/tmp/liveStarstream/Carthage/Checkouts/ParseLiveQuery-iOS-OSX/Carthage/Checkouts/Starscream/zlib/include.h:2:10: note: submodule of top-level module 'SSCommonCrypto' implicitly imported here
#include <CommonCrypto/CommonCrypto.h>
         ^
<unknown>:0: error: could not build Objective-C module 'SSCZLib'

The steps I took are: 
1. Forked ParseLiveQuery-iOS-OSX, modify its Cartfile to point to "vkedwardli/Starscream" "fix-module-redefinition"
2. Changed Cartfile of sample app to: 
github "bayareahank/ParseLiveQuery-iOS-OSX"  "master"
3. Carthage built fine. 
4. Added ParseLiveQuery framework to the sample iOS app. 
5. Build the app itself, it failed with error messages listed above.

**Comment by bayareahank** [comment]
Tried the heck in https://github.com/daltoniam/Starscream/issues/445 by Bersaelor, -- manually remove the SSCZLib and SSCommonCrypto module definitions from Carthage/Checkout/Starscream/zlib/module.modulemap file after Carthage build, that solved the problem for me. FYI.

**Comment by vkedwardli** [comment]
Thanks for the input @bayareahank, I have verified that it is working on Carthage also.

@daltoniam By using SPM's `swift package generate-xcodeproj` in the master branch, the generated xcodeproj cannot locate the SSCZLib/SSCommonCrypto anyways, while using `swift build`, both the master branch and my pull request are building succesfully (since they are both using your zlib-spm and common-crypto-spm)

What is the intended usage for SPM in this project? I thought SPM doesn't support iOS officially?
Thanks

**Comment by vkedwardli** [comment]
The fix in https://github.com/daltoniam/Starscream/pull/520 is more elegant, closing this one.
Would be great if @daltoniam can spend some time to review and accept #520 😁

**Pull request closed without merging**
