### PR TITLE
Client Side Authentication Added

### PR DESCRIPTION
**Pull request by MuniekMg**
Added client certificate for SSL Client Side Authentication with a few methods to obtain it by various of inits.

### CODE REVIEW

**Comment by mateuszjablonski-slabs** [comment]
@daltoniam can you check it?

**Comment by daltoniam** [comment]
Looks good! I released a new version for Swift 4.1 support and that appears to created a conflict 😞. A few things I might suggest changing with the conflict updated:

- No print statements. Those errors should be bubbled up so we can return it to the user.
- I think we can remove the `useSSLClientAuthentication`. The optional `sslClientCertificate` I think should suffice.

Again looks great, just a few small things 😄.

**Comment by MuniekMg** [comment]
@daltoniam All Done! :)

**Comment by fsuc** [comment]
Thanks for this pull request. Can we add another initializer to pass data and password ?

**Comment by MuniekMg** [comment]
@fsuc I think it's question to owner @daltoniam

**Comment by AdamMak** [comment]
Any updates on when this is likely to be approved? Would really like to have this added to Starscream as I require this for my current project.

**Comment by sum98044** [comment]
me too. client certificate authentication is getting popular. 
It would be great it can be approved.

**Comment by wojciech-holisz** [comment]
Please approve it. We also need this in our project.

**Comment by pioole** [comment]
+1

**Comment by daltoniam** [comment]
I'm finally gonna merge this 😄. I still need to do some testing, but I'm going to do that apart of my 4.0.0 release with the Network.framework. Great work and sorry about the delay!

**Pull request merged**
