### PR TITLE
Finds the HTTP Packet in the TCP stream even with empty content

### PR DESCRIPTION
**Pull request by ricardopereira**
#123

### CODE REVIEW

**Comment by ricardopereira** [comment]
Where can I write a test about this fix?

**Comment by mattheworiordan** [comment]
Why not make that method a public method and inject a buffer example that passes and one that fails, but should pass, that this commit fixes?

**Comment by ricardopereira** [comment]
@daltoniam I noticed that there are no tests implemented. What was the last time you run Autobahn Test? I run it yesterday and the result is: https://dl.dropboxusercontent.com/u/11377305/tmp/starscream-report-ws-20151213/clients/index.html. Some of them are failing.

**Comment by daltoniam** [comment]
I haven't added any tests yet. My hope is to create a Swift HTTP/Websocket server that can be used for the tests, but that is going to take a fair amount of work, so I haven't gotten around to it yet. I will take a look at the autobahn tests.

**Comment by daltoniam** [comment]
I was able to look into the failing tests the new `1.1.0` release should resolve this (hopefully we can get a test server created in Swift in the future to have better tests).

**Pull request closed without merging**
